name: IntegrateFromUpstream
on:
  schedule:
    # verified via crontab.guru website. “At 01:00 on Monday.”
    - cron: '0 1 * * 1'
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      message:
        description: 'Reason for manual trigger'
        required: false
        default: 'refresh master'
jobs:
  IntegrateFromUpstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get Current Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Fetch and Merge
        run: |
          echo "Reason for trigger: ${{ github.event.inputs.message }}"
          echo "Actor for trigger: ${{ github.event.actor }}"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote add upstream https://github.com/microsoft/DeepSpeed
          git fetch upstream master
          git merge upstream/master 
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          branch: IFU-master-${{ steps.date.outputs.date }}
          title: IFU-master-${{ steps.date.outputs.date }}
          assignees: jithunnair-amd
          reviewers: jithunnair-amd
